In [2]:
import numpy as np

In [29]:
def power_method(mat):
    '''
    Implementing power method to find eigen vector of largest eigen vector(corresponding to largest eigen value)
    of transformation matrix
    params:
        mat: ndarray of shape (n,n) the transformation matrix
    returns:
        vect: eigen vecotr corresponding to largest eigen value
        val : (max(vect)) largest eign value
    '''
    # 1- initialize the vect with let's say [1,1] (of the n dims) 
    # 2- repeate:
    #   a- normalize vect with inf norm
    #   b- matrix multiplication of the vect and mat (mat @ vect = lambda vect)
    #   c- until vect_new is close to vect old
    # 3- the larges eigen value is the largest component in vect (this is the result of noumalization step we did) 
    vect = np.ones((mat.shape[0], 1), dtype= np.float32)
    vect_old = vect.copy()
    for i in range(1000):
        vect = vect / np.linalg.norm(vect, ord= np.inf)
        vect = mat @ vect
        if np.allclose(vect, vect_old):
            print('n iterations: ',i) # I can remove this (this only to show how long did it take to reach target)
            break
        else:
            vect_old = vect.copy()

    return vect , max(vect)


In [4]:
# matrix to test the power method algorithm (use numpy to verify the solution)
temp = np.array([\
    [.1,.3,.4],
    [.8,.6,.3],
    [.1,.1,.3]
    ])
temp2 = np.array([\
    [1,13,4],
    [8,5,9],
    [7,11,3]
    ])
print(temp)
print(temp2)

[[0.1 0.3 0.4]
 [0.8 0.6 0.3]
 [0.1 0.1 0.3]]
[[ 1 13  4]
 [ 8  5  9]
 [ 7 11  3]]


In [27]:
# assignment propelm one
mat1 = np.array([[0,2],[2,3]])
mat2 = np.array([\
    [-4, 14, 0],
    [-5, 13, 0],
    [-1, 0, 2]
    ])
page_rank_mat =  np.array([\
    [0, .5, 0,  0,  0],
    [0,  0, 0,  0, 1/3],
    [1, .5, 0, .5, 1/3],
    [0,  0, 1,  0, 1/3],
    [0,  0, 0, .5,  0],
    ])

In [34]:
mat1vect, mat1val = power_method(mat1)
print('problem 1 mat1 eigvect is: ',mat1vect)
print('problem 1 mat1  eigval is: ',mat1val)
print()
mat2vect, mat2val = power_method(mat2)
print('problem 1 mat2 eigvect is: ',mat2vect)
print('problem 1 mat2 eigval is: ',mat2val)
print()
rankvect, rankval = power_method(page_rank_mat)
print('problem 2 page rank vector is: ',rankvect)
# print('problem 2 mat2 eigval is: ',rankval)

n iterations:  9
problem 1 mat1 eigvect is:  [[2.        ]
 [3.99999682]]
problem 1 mat1  eigval is:  [3.99999682]

n iterations:  16
problem 1 mat2 eigvect is:  [[ 6.00002616]
 [ 4.28573858]
 [-1.49998692]]
problem 1 mat2 eigval is:  [6.00002616]

n iterations:  27
problem 2 page rank vector is:  [[0.08333344]
 [0.1666672 ]
 [0.83333391]
 [1.00000315]
 [0.5       ]]
